CREATE TABLE clients (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(75) NOT NULL,
lastname VARCHAR(75) NOT NULL,
docnumber VARCHAR(11)  NOT NULL);

CREATE TABLE invoices (
id INT AUTO_INCREMENT PRIMARY KEY,
client_id INT NOT NULL,
created_at DATETIME NOT NULL,
total DOUBLE NOT NULL,
FOREIGN KEY (client_id) REFERENCES clients(id));

CREATE TABLE products (
id INT AUTO_INCREMENT PRIMARY KEY,
description VARCHAR(150) NOT NULL,
code VARCHAR(50) NOT NULL,
stock INT NOT NULL,
price DOUBLE NOT NULL);

CREATE TABLE invoice_details (
invoice_id INT NOT NULL,
invoice_detail_id INT AUTO_INCREMENT PRIMARY KEY,
amount INT NOT NULL,
product_id INT NOT NULL,
price DOUBLE NOT NULL,
FOREIGN KEY (invoice_id) REFERENCES invoice(id),
FOREIGN KEY (product_id) REFERENCES products(id)
);
